set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME
syntax on
filetype plugin indent on
set colorcolumn=80

set wildmenu            " visual autocomplete for cmd menu
set lazyredraw          " redraw only when needed

inoremap " ""<left>
inoremap ' ''<left>
inoremap ( ()<left>
inoremap [ []<left>
inoremap { {}<left>
inoremap {<CR> {<CR>}<ESC>O

" Line numbering
set number
set relativenumber

function! NumberToggle()
  if(&relativenumber == 1)
    set norelativenumber
  else
    set relativenumber
  endif
endfunc
nnoremap <C-n> :call NumberToggle()<cr>

" Backspace
set backspace=indent,eol,start
set whichwrap+=<,>,h,l

" Searching
set ignorecase
set incsearch           " search whilst entering
set hlsearch            " highlight matches

" Folding
set foldenable          " enable folding
set foldlevelstart=10   " open most by default
set foldnestmax=10      " 10 nested fold max
set foldmethod=indent   " fold based on indent level

" Managing those pesky tabs and spaces
" Standard tab equals four spaces
set shiftwidth=4
set softtabstop=4
set expandtab
" Toggle between tab being 4 spaces (Python ed)
" and an actual tab of eight columns (Linux kernel style)
function ToggleTab()
    if &expandtab
        set shiftwidth=8
        set softtabstop=0
        set noexpandtab
    else
        set shiftwidth=4
        set softtabstop=4
        set expandtab
    endif
endfunction
